coverage:
  status:
    project:
      default:
        target: auto
        threshold: null
      index:
        flags: index
        target: 75%
      demo:
        flags: demo
        target: 80%
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: no        
  require_head: yes       
  branches: null

flags:
  demo:
    paths:
      - /src/demo.py
  index:
      - /src/index.py

ignore:
  - "request.py"
